"""create vkfriends table

Revision ID: 121177af8158
Revises: bfe058ade1fd
Create Date: 2022-06-13 20:25:58.737943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121177af8158'
down_revision = 'bfe058ade1fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vkfriends', sa.Column('bdate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vkfriends', 'bdate')
    # ### end Alembic commands ###
