"""create vkcities table relation

Revision ID: 5633a6d4f5e5
Revises: 121177af8158
Create Date: 2022-06-13 22:52:49.177332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5633a6d4f5e5'
down_revision = '121177af8158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vkcities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'vkfriends', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vkfriends', 'vkcities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vkfriends', type_='foreignkey')
    op.drop_column('vkfriends', 'city_id')
    op.drop_table('vkcities')
    # ### end Alembic commands ###
