"""create vkfriends table

Revision ID: bfe058ade1fd
Revises:
Create Date: 2022-06-13 20:17:32.133554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe058ade1fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vkfriends',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('vk_id', sa.Integer(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('sex', sa.Integer(), nullable=True),
        sa.Column('nickname', sa.String(), nullable=True),
        sa.Column('domain', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vkfriends')
    # ### end Alembic commands ###
