"""add avatar

Revision ID: eda5d38f16c3
Revises: c834eb25ec6f
Create Date: 2022-09-18 23:28:21.277760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda5d38f16c3'
down_revision = 'c834eb25ec6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userentities', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userentities', 'avatar')
    # ### end Alembic commands ###
